### PR TITLE
Issue/60/gridded_input

### PR DESCRIPTION
**Pull request by aimalz**
I implemented initialization and plotting of gridded input to prepare for #55.

### CODE REVIEW

**Review by drphilmarshall — CHANGES_REQUESTED** [review]
Looks good, Alex. I am still a bit confused by what is being assumed in the "Binning Parametrization", so I think it'd be good to make that clear. To my mind, "binning" is what you do to samples, whereas "gridding" or "tabulating" is what you do when evaluating a continuous function at a set of (usually regularly-spaced) points. Likewise, a "histogram" is, at least in my mind, conceptually different from a "piece-wise constant function" approximation. You make histograms from samples, and the result is a piece-wise constant approximation of the sampled PDF. However, you don't need to make samples and then a histogram in order to approximate a continuous function with a piece-wise constant representation. (You can do the integrals by methods other than Monte Carlo!) This is important because if we use the terms "binning" or "histogram" they imply a piece-wise constant function approximation. If we interpolate between bin centers with anything other than a piece-wise constant function, that is an additional approximation choice that we need to make explicit: this choice of interpolation will matter, and so when I query the PDF object's approximation method the interpolation choice somehow needs to be exposed. This demo doesn't yet make it clear how this is handled, I think. How about we add some statements printing out the PDF object attribute that tells the user what approximation is currently being used?

**Comment by drphilmarshall** [comment]
I'm having a go at this - watch out for new commits! :-)

**Comment by aimalz** [comment]
I've been taking "binning" to mean that the bin values are integrals of the probability density within the bounds of the bin, which does not need to be calculated from samples.  Perhaps this should be distinguished from "histogramizing," which we've so far been using synonymously.  I can add some notes to the docstrings explaining this if we agree on the meaning.

**Comment by drphilmarshall** [comment]
Sounds good - I went through the notebook and made some edits, and updated the code to match. "Gridded" and "evaluated" are used synonymously, it seems - maybe the parametrization should be "gridded", to avoid conflict with the `qp.PDF.evaluate()` method? I don't think it matters much though. Great if you can take a look and iterate again? Thanks!

**Comment by aimalz** [comment]
Thanks, I took your advice and changed the variable/keywords to be consistent with the "gridding" language, and the notebook still works.  Are we ready to merge?

**Review by drphilmarshall — APPROVED** [review]
Excellent! I think this is good to go. Nice work!

**Pull request merged**
