### PR TITLE
Issue/39/start paper

### PR DESCRIPTION
**Pull request by aimalz**
Re: #39 the zeroth version of the draft is ready.  @drphilmarshall does it look okay to you?  Thanks for getting this started!

### CODE REVIEW

**Comment by aimalz** [comment]
Oh, it just occurred to me that the Travis checks won't find errors in the paper.  For example, what I just pushed fails upon running `make`.  (I have not yet investigated the cause of the error but will do so immediately.)  Should I add compilation of it to the `.yml`?

**Comment by drphilmarshall** [comment]
Yes! There should be a .travis.yml that came with the `start_paper`
template that you can copy and paste from to not only build the paper, but
also deploy the built PDF back to the base repo in an orphan `pdf` branch.
Good catch!

An important step in this process is to obtain a GitHub API key (see your
settings), and paste it into the travis repo settings as an environment
variable called `GITHUB_API_KEY`, that it can look up and use to push the
PDF back to GitHub.

**Comment by aimalz** [comment]
It took me far too long to find the [documentation](https://github.com/LSSTDESC/start_paper/tree/master/doc/desc-0000-start_paper-intro#automatic-pdf-sharing) for this procedure, but I think I followed the instructions.  Am I correct in understanding that we won't find out for sure if it worked until the branch is merged into `master`?

**Comment by drphilmarshall** [comment]
Yes, that's right - I'll review now so you can merge and try it out!

**Review by drphilmarshall — APPROVED** [review]
OK, I made some logistical tweaks, and the main tex file looks in good enough shape to close #39. Nice!

**Comment by aimalz** [comment]
It looks like after merging this, the .pdf isn't being updated on GitHub (which is corroborated by [Travis](https://travis-ci.org/aimalz/qp/builds/213198641)).  I was under the impression that it didn't matter if the changes were made in the .travis.yml in the paper directory rather than the top-level directory (and the rest of the commands there seem to have worked), but I don't have other ideas for what might be wrong.

**Comment by drphilmarshall** [comment]
I'll take a look and issue a fix. My success rate in getting this to work first time is about 50% :-)

**Pull request merged**
