### PR TITLE
Simple notebook trying to interpret the magnitude of the KL divergence

### PR DESCRIPTION
**Pull request by drphilmarshall**
This is in response to #29. Check it out, @aimalz ! 

BTW. I put the notebook in the top level folder, but when we merge #28 we'll need to move it into `docs/notebooks`.

### CODE REVIEW

**Review by aimalz — APPROVED** [review]
Looks good!

**Comment by aimalz** [comment]
I just worked through the notebook myself and wanted to say bravo, @drphilmarshall, for a job well done!

**Comment by drphilmarshall** [comment]
Thanks @aimalz ! Do you want to issue yourself with replacing my guessed models (and their interpretation) with your analytic derivation (and its interpretation)? From what I could see, the precision conclusions are unchanged but your tension definition is different, which is interesting!

**Comment by aimalz** [comment]
On it!  I created #34 and assigned it to myself.

**Pull request merged**
